### ISSUE TITLE
Collecting ideas for little JS quizzes

### ISSUE THREAD

**Issue by TheAmazingPT** [transforvolving/wtm-website#3]
As discussed after the event, we want to collect some ideas for quizzes or games as an introduction to JS for our students.

I think its important to agree on certain questions like how deep you want to go into the topic, how broad you want to use the tool set and how often to you want to reiterate on the idea. Maybe it makes sense to have many small ideas for various different topics in the world of JS or to have one big idea, which gets enhanced step by step. A relation to our WTMHH website would be delightful.

**Comment by ilithya** [comment]
@TheAmazingPT Pss, so Steffi wrote the Scroll To Top function for our link.
I revised it and look it together with her. Then we look at your counter. Btw. I fixed a small typo in the hours variable that was causing the console to show an error.

And anyways, ECMAScript6 is certainly advance for us, that we'd like you to take a look at her code, and edit it if we do want to show only ECMAScript6 vanilla JS at the Workshop.

Otherwise, if it doesn't matter is other vanilla JS, we can leave it as it is.
What do you think? 

Just pull and you'll find the changes.

**Comment by ilithya** [comment]
@TheAmazingPT Ok, in fact I just tried to convert Steffi's vanilla JS into ECMAScrip6. Not the best I guess, but after you pull, you'll find her original code and my conversion edits.
